# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weights.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weights.proto',
  package='yantk',
  syntax='proto2',
  serialized_pb=_b('\n\rweights.proto\x12\x05yantk\"\xa3\x01\n\x07Weights\x12\x0e\n\x06w_h_00\x18\x01 \x02(\x02\x12\x0e\n\x06w_h_01\x18\x02 \x02(\x02\x12\x0e\n\x06w_h_10\x18\x03 \x02(\x02\x12\x0e\n\x06w_h_11\x18\x04 \x02(\x02\x12\x0b\n\x03\x62_0\x18\x05 \x02(\x02\x12\x0b\n\x03\x62_1\x18\x06 \x02(\x02\x12\x0e\n\x06w_o_00\x18\x07 \x02(\x02\x12\x0e\n\x06w_o_01\x18\x08 \x02(\x02\x12\x0e\n\x06w_o_10\x18\t \x02(\x02\x12\x0e\n\x06w_o_11\x18\n \x02(\x02\"F\n\x10IterationWeights\x12\x11\n\titeration\x18\x01 \x02(\x05\x12\x1f\n\x07weights\x18\x02 \x02(\x0b\x32\x0e.yantk.Weights\"E\n\x0fTrainingWeights\x12\x32\n\x11iteration_weights\x18\x01 \x03(\x0b\x32\x17.yantk.IterationWeights')
)




_WEIGHTS = _descriptor.Descriptor(
  name='Weights',
  full_name='yantk.Weights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w_h_00', full_name='yantk.Weights.w_h_00', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_h_01', full_name='yantk.Weights.w_h_01', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_h_10', full_name='yantk.Weights.w_h_10', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_h_11', full_name='yantk.Weights.w_h_11', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b_0', full_name='yantk.Weights.b_0', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b_1', full_name='yantk.Weights.b_1', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_o_00', full_name='yantk.Weights.w_o_00', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_o_01', full_name='yantk.Weights.w_o_01', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_o_10', full_name='yantk.Weights.w_o_10', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w_o_11', full_name='yantk.Weights.w_o_11', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=188,
)


_ITERATIONWEIGHTS = _descriptor.Descriptor(
  name='IterationWeights',
  full_name='yantk.IterationWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iteration', full_name='yantk.IterationWeights.iteration', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weights', full_name='yantk.IterationWeights.weights', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=260,
)


_TRAININGWEIGHTS = _descriptor.Descriptor(
  name='TrainingWeights',
  full_name='yantk.TrainingWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iteration_weights', full_name='yantk.TrainingWeights.iteration_weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=331,
)

_ITERATIONWEIGHTS.fields_by_name['weights'].message_type = _WEIGHTS
_TRAININGWEIGHTS.fields_by_name['iteration_weights'].message_type = _ITERATIONWEIGHTS
DESCRIPTOR.message_types_by_name['Weights'] = _WEIGHTS
DESCRIPTOR.message_types_by_name['IterationWeights'] = _ITERATIONWEIGHTS
DESCRIPTOR.message_types_by_name['TrainingWeights'] = _TRAININGWEIGHTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Weights = _reflection.GeneratedProtocolMessageType('Weights', (_message.Message,), dict(
  DESCRIPTOR = _WEIGHTS,
  __module__ = 'weights_pb2'
  # @@protoc_insertion_point(class_scope:yantk.Weights)
  ))
_sym_db.RegisterMessage(Weights)

IterationWeights = _reflection.GeneratedProtocolMessageType('IterationWeights', (_message.Message,), dict(
  DESCRIPTOR = _ITERATIONWEIGHTS,
  __module__ = 'weights_pb2'
  # @@protoc_insertion_point(class_scope:yantk.IterationWeights)
  ))
_sym_db.RegisterMessage(IterationWeights)

TrainingWeights = _reflection.GeneratedProtocolMessageType('TrainingWeights', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGWEIGHTS,
  __module__ = 'weights_pb2'
  # @@protoc_insertion_point(class_scope:yantk.TrainingWeights)
  ))
_sym_db.RegisterMessage(TrainingWeights)


# @@protoc_insertion_point(module_scope)
